development:
  adapter: postgresql
  encoding: unicode
  database: plain_errors_dev
  pool: 5
  user: chris

test: &test
  adapter: postgresql
  encoding: unicode
  database: plain_errors_test
  pool: 5

